name: CI/CD Build Docker Image, Push to Docker Hub, and Deploy to AWS EC2

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arjunkan22/timgaze-image:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create PEM file from secret
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > timegaze.pem

      - name: Set permissions for PEM file
        run: chmod 600 timegaze.pem
        
      - name: Pull Docker image and run container
        run: |
          ssh -i "timegaze.pem" -o StrictHostKeyChecking=no ubuntu@ec2-13-232-247-163.ap-south-1.compute.amazonaws.com << 'EOF'
            sudo docker stop timegaze || true
            sudo docker rm timegaze || true
            sudo docker rmi arjunkan22/timgaze-image:latest || true
            sudo docker pull arjunkan22/timgaze-image:latest
            sudo docker run -d --name timgaze -p 4000:4000 -v ${PWD}/public/uploads:/src/public/uploads --env-file .env arjunkan22/timgaze-image
          EOF
      
      - name: Cleanup PEM file
        run: rm timegaze.pem
